Завдання 1. В25. Створіть одновимірний масив (вектор) з сумами добутків двох попередніх чисел та 
їхнього суми, починаючи з 1, та виведіть його значення.

In [5]:
import numpy as np
n = 5
array = np.zeros(n)
array[0], array[1] = 1, 1 
for i in range(2, n):
    mult = array[i-1] * array[i-2]
    sum_prev = array[i-1] + array[i-2]
    array[i] = mult + sum_prev
print(array)

[ 1.  1.  3.  7. 31.]


Завдання 2. В25. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його значеннями 
випадкових цілих чисел від -10 до 10.


In [4]:
mat = np.random.randint(-10, 11, size=(3, 3))
print(mat)

[[ -3  -4  -8]
 [  6   6   1]
 [-10  -8   5]]


Завдання 3. В25. Створіть масив розміром 5x5, заповніть його випадковими дійсними числами від 0 до 
1 та знайдіть відсоток чисел, які є простими.

In [13]:
matrix = np.random.rand(5, 5)
rounded_matrix = np.round(matrix * 100).astype(int)

def is_prime(n):
    if n <= 1:
        return False
    if n == 2 or n == 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

prime_count = np.sum(np.vectorize(is_prime)(rounded_matrix))
total_elements = matrix.size
perc = (prime_count / total_elements) * 100

print("випадкові числа:")
print(matrix)
print("\nокруглена матриця:")
print(rounded_matrix)
print("Відсоток простих чисел:", perc,"%")

випадкові числа:
[[0.93927341 0.46962453 0.42863147 0.26209653 0.87440186]
 [0.96154891 0.12859165 0.69737153 0.75009596 0.94721752]
 [0.3438613  0.19171578 0.90525399 0.8365918  0.20760243]
 [0.03937084 0.8731452  0.09626807 0.32054384 0.37350028]
 [0.12220922 0.48677735 0.03086771 0.70472589 0.70100549]]

округлена матриця:
[[94 47 43 26 87]
 [96 13 70 75 95]
 [34 19 91 84 21]
 [ 4 87 10 32 37]
 [12 49  3 70 70]]
Відсоток простих чисел: 24.0 %


Завдання 4.В25. Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в 
діапазоні від -1.1 до 1.1 та виведіть його значення.

In [14]:
matrix = np.random.uniform(-1.1, 1.1, (3, 3))
print(matrix)

[[-0.07404784 -0.91832054  0.89012039]
 [ 0.31424143 -1.00262903 -0.9872368 ]
 [ 0.63305614  0.22427198  0.78060038]]


Завдання 5. В25. Створіть два одновимірних масиви розміром 4, заповніть їх випадковими цілими 
числами в діапазоні від 15 до 25 та виконайте на них поелементні операції додавання, 
віднімання та множення

In [17]:
arr1 = np.random.randint(15, 26, 4)
arr2 = np.random.randint(15, 26, 4)

add = arr1 + arr2
sub = arr1 - arr2
mult = arr1 * arr2
print("array 1", arr1)
print("array 2", arr2)
print("add", add)
print("sub",sub)
print("mult",mult)

array 1 [15 25 18 23]
array 2 [17 20 21 24]
add [32 45 39 47]
sub [-2  5 -3 -1]
mult [255 500 378 552]


Завдання 6. В25. Створіть дві матриці 3x3, заповніть їх довільними цілими числами від 1 до 10 та 
знайдіть їх добуток.


In [19]:
matrix1 = np.random.randint(1, 11, (3, 3))
matrix2 = np.random.randint(1, 11, (3, 3))
print(np.dot(matrix1, matrix2))

[[ 57 177 108]
 [ 20  70  68]
 [ 16  37  30]]


Завдання 7.В25. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами 
в діапазоні від 1 до 5 та перемножте їх між собою

In [20]:
matrix1 = np.random.randint(1, 6, (2, 3))
matrix2 = np.random.randint(1, 6, (3, 3))
print(np.dot(matrix1, matrix2))

[[23 24 32]
 [21 38 44]]


Завдання 8. В25. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні 
від 1 до 7 та знайдіть її обернену матрицю.

In [24]:
matrix = np.random.randint(1, 8, (2, 2))
inverse_matrix = np.linalg.inv(matrix)
print("original matrix\n",matrix)
print("reversed matrix\n",inverse_matrix)

original matrix
 [[7 3]
 [7 1]]
reversed matrix
 [[-0.07142857  0.21428571]
 [ 0.5        -0.5       ]]


Завдання 9. В25. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
діапазоні від 5 до 10 та транспонуйте її.


In [29]:
matrix = np.random.uniform(5, 10, (3, 3))
print("origin matrix\n",matrix)
print("trans matrix\n",matrix.T)

origin matrix
 [[9.18957005 9.14928532 5.25226956]
 [7.29420033 5.42564235 8.74262955]
 [6.34244598 9.09951197 9.62002245]]
trans matrix
 [[9.18957005 7.29420033 6.34244598]
 [9.14928532 5.42564235 9.09951197]
 [5.25226956 8.74262955 9.62002245]]


Завдання 10.В25. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю 
випадковими дійсними числами від 0 до 1, а вектор - випадковими дійсними числами 
від 0 до 1, і знайдіть добуток матриці на вектор.

In [36]:
matrix = np.random.rand(3, 4)
vector = np.random.rand(4, 1)
print("matrix\n",matrix)
print("vector\n",vector)
print("dobytok\n",np.dot(matrix, vector))

matrix
 [[0.85048902 0.68177568 0.13580784 0.34236911]
 [0.86125129 0.33363363 0.35361034 0.21281798]
 [0.60460831 0.64531403 0.27057466 0.77554914]]
vector
 [[0.11937108]
 [0.83440953]
 [0.91992798]
 [0.9999865 ]]
dobytok
 [[1.13770184]
 [0.91930673]
 [1.6350768 ]]


Завдання 11.В25. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю 
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими цілими 
числами в діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.


In [39]:
matrix = np.random.randint(1, 11, (2, 3))
vector = np.random.randint(1, 11, (3, 1))
result = np.dot(matrix, vector)
print("matrix:")
print(matrix)
print("vector:")
print(vector)
print("matrix*vector:")
print(result)

matrix:
[[ 3  1  8]
 [10  5  9]]
vector:
[[9]
 [1]
 [6]]
matrix*vector:
[[ 76]
 [149]]


Завдання 12.В25. Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в 
діапазоні від -2 до 2 та знайдіть суму всіх елементів обох матриць

In [42]:
matrix1 = np.random.randint(-2, 3, (2, 2))
matrix2 = np.random.randint(-2, 3, (2, 2))
total_sum = np.sum(matrix1) + np.sum(matrix2)
print("matrix 1:")
print(matrix1)
print("matrix2:")
print(matrix2)
print("sum of elements:",total_sum)

matrix 1:
[[ 2  2]
 [-2  1]]
matrix2:
[[-1  0]
 [-1 -1]]
sum of elements: 0


Завдання 13.В25. Створіть дві матриці розміром 3x3, заповніть їх випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть суму їх елементів.


In [43]:
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
total = np.sum(matrix1) + np.sum(matrix2)
print("matrix 1:")
print(matrix1)
print("\nmatrix 2:")
print(matrix2)
print("сума елекментів матриць:",total)

matrix 1:
[[0.47898967 0.70775721 0.29787319]
 [0.18443886 0.26877228 0.80605963]
 [0.0567912  0.26782199 0.78494978]]

matrix 2:
[[0.7002281  0.27079877 0.86848724]
 [0.21084553 0.79465481 0.20579676]
 [0.02417164 0.95537531 0.22506491]]
сума елекментів матриць: 8.108876857220109


Завдання 14. В25. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
діапазоні від -10 до 10 та знайдіть суму елементів на побічній діагоналі

In [44]:
matrix = np.random.uniform(-10, 10, (3, 3))
diagonal_sum = np.sum(np.fliplr(matrix).diagonal())
print("Matrix:")
print(matrix)
print("sum of elements on side diagonal", diagonal_sum)

Matrix:
[[ 0.47774084 -7.24210907  5.17387996]
 [ 1.68763766  2.02180666  1.16849869]
 [-6.54881235 -1.1240916   1.04368307]]
sum of elements on side diagonal 0.646874268805318


In [ ]:
Завдання 15.В25. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в 
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить найбільший елемент у 
кожному стовпці матриці

In [45]:
matrix = np.random.rand(3, 3)
max_in_columns = np.max(matrix, axis=0)
print("matrix:")
print(matrix)
print("\nmax num in each column:")
print(max_in_columns.reshape(-1, 1))

matrix:
[[0.39800268 0.69627565 0.57208194]
 [0.99430042 0.81561164 0.1424263 ]
 [0.42940736 0.44495761 0.18832071]]

max num in each column:
[[0.99430042]
 [0.81561164]
 [0.57208194]]


Висновок:За цю лабораторну роботу були використані різні функції роботи з матрицями за допомогою бібліотеки numpy.